### ISSUE TITLE
missing UI sti-files for german version

### ISSUE THREAD

**Issue by kitty624** [1dot13/gamedir-languages#7]
ITEMINFOADVANCEDICONS.sti is missing in german version

can probably be fixed by copying the one from english version (this shouldn't contain any text)

i recall simular issues with UI for autoresolve 

assumed that this is probably an issue happening for a lot of files this requires more testing (playthroughs in german)

**Comment by Asdow** [comment]
Closing this as completed, since that file is now loaded from the base interface directory for all languages
